name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: "Build with JDK${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Use both LTS releases and latest one
        jdk: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: >
            ./routing-core/build/reports/jacoco/test/jacocoTestReport.xml,
            ./routing-dsl/build/reports/jacoco/test/jacocoTestReport.xml,
            ./routing-coroutines/build/reports/jacoco/test/jacocoTestReport.xml,
            ./routing-annotations/routing-annotated/build/reports/jacoco/test/jacocoTestReport.xml